baseurl = "https://michaelneuper.netlify.app"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-US"
theme = "classic"
title = "Michael"

[taxonomies]
   tag = "tags"
   category = "categories"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

  # [[menu.main]]
  # name = "Categories"
  # url = "/categories/"
  # weight = 1

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2

  [[menu.feed]]
  name = "GitHub"
  url = "https://github.com/michaelneuper"

[params]
custom_css = ["css/theme-override.css"]
description = "A simple, minimal blog for those who love text."
footer = "Copyright © 2022 Michael Neuper | [Source](https://github.com/michaelneuper/website)"
