title = "Michael"
baseurl = "https://michaelneuper.com"
theme = "classic"
languageCode = "en-US"
enableEmoji = true
footnotereturnlinkcontents = "↩"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[taxonomies]
category = "categories"
tag = "tags"

[outputs]
home = ["RSS", "HTML"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 2

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.feed]]
name = "RSS"
url = "/index.xml"

[[menu.feed]]
name = "github"
url = "https://github.com/michaelneuper"

[params]
custom_css = ["css/theme-override.css"]
favicon = "images/favicon.ico"
description = ""
footer = "Copyright © 2023 Michael Neuper | [Source](https://github.com/michaelneuper/website)"
