baseURL = "https://michaelneuper.com"
disqusShortname = ""
enableGitInfo = false
enableRobotsTXT = true
googleAnalytics = "G-0GZRVRLSQV"
hasCJKLanguage = true
languageCode = "en"
paginate = 5
rssLimit = 10
theme = "hugo-texify2"
title = "Michael's Site"

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/"
weight = 1
[[menu.main]]
identifier = "pages"
name = "About"
url = "/pages/"
weight = 2

[taxonomies]
tags = "tags"
categories = "categories"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe= true
[markup.highlight]
style = "solarized-light"
[markup.tableOfContents]
  endLevel = 6
  ordered = false
  startLevel = 2

[author]
email = "michael@michaelneuper.com"
name = "Michael Neuper"

[params]
title="Michael's Site"
description = "TeXify2 - a minimal, latex-style hugo theme for personal blogging"
images = ['images/logo.png']
footnote = """
Follow me on <a class=link href=https://github.com/michaelneuper target=_blank rel=noopener>GitHub</a> or
<a class=link href=/index.xml>RSS</a>
"""
keywords = ["hugo", "latex", "theme", "blog", "texify", "texify2", "weastur"]
customCSS = ["css/styles.css"]
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
since = "2022"
toc = true
showWordCount = false
showReadingTime = true
rootFontSize = "100%"
math = true
enableDuckDuckGoSearchBox = false
numberedSubtitles = true

[params.commentEngine]
code = """
"""

[params.buymeacoffee]
code = """
<script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="weastur" data-description="Support me on Buy me a coffee!" data-message="" data-color="#FF5F5F" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
"""

[params.sharingbuttons]
facebook = false
twitter = false
email = false
linkedin = false
reddit = false
whatsapp = false
hackernews = false
telegram = false