baseURL = "https://michaelneuper.com"
disqusShortname = ""
enableGitInfo = false
enableRobotsTXT = true
googleAnalytics = "G-BLX24KP7CS"
hasCJKLanguage = true
languageCode = "en"
paginate = 3
rssLimit = 10
theme = "hugo-texify2"
title = "Michael's Site"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "post"
name = "Blog"
url = "/post/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
tags = "tags"
categories = "categories"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe= true
[markup.highlight]
style = "base16-solarized-dark"
[markup.tableOfContents]
  endLevel = 6
  ordered = false
  startLevel = 2

[author]
email = "michael@michaelneuper.com"
name = "Michael Neuper"

[params]
title="Hi, I'm Michael"
description = "Michael's Personal Website"
footnote = """
Follow me on <a class=link href=https://github.com/michaelneuper target=_blank rel=noopener>GitHub</a> or
<a class=link href=/index.xml>RSS</a>
"""
keywords = ["michael", "neuper", "linux", "blog", "productivity"]
customCSS = ["css/styles.css"]
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
since = "2022"
toc = true
showWordCount = false
showReadingTime = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = false
numberedSubtitles = true

[params.buymeacoffee]
code = """
<script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="michaelneuper" data-description="Like what I do? Buy me a coffee!" data-message="" data-color="#b58900" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
"""

[params.sharingbuttons]
facebook = false
twitter = false
email = false
linkedin = false
reddit = false
whatsapp = false
hackernews = false
telegram = false