baseURL = "https://michaelneuper.com"
disqusShortname = ""
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
googleAnalytics = "G-BLX24KP7CS"
hasCJKLanguage = false
languageCode = "en"
rssLimit = 10
theme = "hugo-texify2"
title = "Michael's Site"

[[menu.main]]
identifier = "post"
name = "Blog"
url = "/post/"
weight = 1

[[menu.main]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = 2

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/michaelneuper"
weight = 3

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/pages/contact/"
weight = 4

[taxonomies]
tags = "tags"
categories = "categories"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe= true
[markup.highlight]
noClasses = false
[markup.tableOfContents]
  endLevel = 6
  ordered = false
  startLevel = 2

[author]
email = "michael@michaelneuper.com"
name = "Michael Neuper"

[params]
title="Michael Neuper"
description = "Michael's Personal Website"
footnote = """
<!-- Follow me on <a class=link href=https://github.com/michaelneuper target=_blank rel=noopener>GitHub</a> or
<a class=link href=/index.xml>RSS</a> -->
"""
keywords = ["michael", "neuper", "linux", "blog", "productivity"]
customCSS = ["css/styles.css", "css/syntax.css"]
customJS = ["js/script.js"]
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
showWordCount = false
showReadingTime = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true

[params.commentEngine]
code = """
<script src="https://giscus.app/client.js"
        data-repo="michaelneuper/website"
        data-repo-id="R_kgDOIjPNaQ"
        data-category="General"
        data-category-id="DIC_kwDOIjPNac4CaklA"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="https://github.com/michaelneuper/website/static/css/styles.css"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
"""

[params.buymeacoffee]
code = """
<script data-name="BMC-Widget" 
        data-cfasync="true" 
        src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" 
        data-id="michaelneuper" 
        data-description="Like what I do? Buy me a coffee!" 
        data-message="" 
        data-color="#b58900" 
        data-position="Right" 
        data-x_margin="18" 
        data-y_margin="18"
        crossorigin="anonymous">
</script>
"""

[params.sharingbuttons]
facebook = false
twitter = false
email = false
linkedin = false
reddit = false
whatsapp = false
hackernews = false
telegram = false
