[build.environment]
HUGO_VERSION = "0.115.1"
DART_SASS_VERSION = "1.63.6"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  hugo --gc --minify \
  """

[[headers]]
for = "/*.css"
  [headers.values]
  Cache-Control = "max-age=31536000"

[[headers]]
for = "/*.js"
  [headers.values]
  Cache-Control = "max-age=31536000"

[[headers]]
for = "/*.jpg"
  [headers.values]
  Cache-Control = "max-age=604800"

[[headers]]
for = "/*.jpeg"
  [headers.values]
  Cache-Control = "max-age=604800"

[[headers]]
for = "/*.png"
  [headers.values]
  Cache-Control = "max-age=604800"

[[headers]]
for = "/*.gif"
  [headers.values]
  Cache-Control = "max-age=604800"

[[headers]]
for = "/*"
  [headers.values]
  Cache-Control = "max-age=3600"
  X-Content-Type-Options = "nosniff"
  Content-Encoding = "gzip"
